### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ksherlock** [ksherlock/gs-gopher#1]
- [ ] Option to download an item instead of displaying as a text file (Command-Down Arrow?). Example: BSQ files
- [x] Option to process BSQ files 😄 
- [x] Indicate when a download is in progress (color cycle apple? menu animation?)
- [x] Add timeout for downloading; particularly when connecting.
- [ ] Use grey color for shadow
- [x] Theme support (NeXT, Standard)
- [ ] Bookmarks Menu
- [x] Windows Menu
- [x] Apple-~ to switch windows?
- [ ] Command-R to reload the page
