### ISSUE TITLE
Text TODO

### ISSUE THREAD

**Issue by ksherlock** [ksherlock/gs-gopher#3]
- [x] search
- [x] adjust tab sizes
- [ ] text encoding (convert utf-8 to macroman)
- [ ] de-dot (convert leading .. -> . )
